import Head from 'next/head'
import {Layout} from '../components/layouts/index.js'
import {pokeApi} from '../api'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout 
          title="Pokémon App"
          description="Descripcion de la página"
          keywords="pokemon, app, nextjs"
        >
        </Layout>
      </main>
    </>
  )
}


export const getStaticProps = async () => {
  const {data} = await pokeApi.get('/pokemon?limit=151');
  //images && id
  const pokemons = data.results.map((pokemon, index) => {
    const id = index + 1;
    const image = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${id}.svg`
    return { ...pokemon, id, image }
  })
  console.log(pokemons);
  return {
    props: {}
  }
}